### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by Newyears1978** [journocode/leaflet-search-example#1]
Search is not functioning, all it does is reset to the default viewport no matter what you type in the box.

Crap I did not realize it is a search that pops up matches, I was hitting enter.

**Comment by enigmoe** [comment]
Thanks for checking this! If I understand you correctly, and after checking the corresponding tutorial on our [website](https://journocode.com/2017/02/javascript-interactive-map-with-search-bar-leaflet/), the search does work, so I will close this now. If I am mistaken, please let me know.
